# Copyright 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

apiVersion: skaffold/v4beta14
kind: Config
metadata:
  name: nats-csc
.natsReleaseBase: &nats_release_base
  name: nats-event-bus
  chartPath: ../../deploy/nats-event-bus
  namespace: event-bus
  createNamespace: true
  wait: true
  setValues:
    auth-callout.image.repository: localhost:5001/auth-callout
    auth-callout.image.tag: local
    auth-callout.image.pullPolicy: Always
requires:
  - path: skaffold.auth-callout-image.yaml
    configs:
      - auth-callout-image
  - path: skaffold.secrets.yaml
    configs:
      - nats-secrets-csc
  - path: ../infra/skaffold.yaml
    configs:
      - infra-csc
deploy:
  kubeContext: kind-csc
  statusCheck: true
  statusCheckDeadlineSeconds: 600
  tolerateFailuresUntilDeadline: true
  helm:
    flags:
      depBuild:
        - --repository-config=local/helm/repositories.yaml
    releases:
      - <<: *nats_release_base
        valuesFiles:
          - k8s/local-dev-values.yaml
          - k8s/csc/values.yaml
---
apiVersion: skaffold/v4beta14
kind: Config
metadata:
  name: nats-cpc-1
requires:
  - path: skaffold.auth-callout-image.yaml
    configs:
      - auth-callout-image
  - path: skaffold.secrets.yaml
    configs:
      - nats-secrets-cpc-1
  - path: ../infra/skaffold.yaml
    configs:
      - infra-cpc-1
deploy:
  kubeContext: kind-cpc-1
  statusCheck: true
  statusCheckDeadlineSeconds: 600
  tolerateFailuresUntilDeadline: true
  helm:
    flags:
      depBuild:
        - --repository-config=local/helm/repositories.yaml
    releases:
      - <<: *nats_release_base
        valuesFiles:
          - k8s/local-dev-values.yaml
          - k8s/cpc/values.yaml
          - k8s/cpc/cpc-1.yaml
---
apiVersion: skaffold/v4beta14
kind: Config
metadata:
  name: nats-cpc-2
requires:
  - path: skaffold.auth-callout-image.yaml
    configs:
      - auth-callout-image
  - path: skaffold.secrets.yaml
    configs:
      - nats-secrets-cpc-2
  - path: ../infra/skaffold.yaml
    configs:
      - infra-cpc-2
deploy:
  kubeContext: kind-cpc-2
  statusCheck: true
  statusCheckDeadlineSeconds: 600
  tolerateFailuresUntilDeadline: true
  helm:
    flags:
      depBuild:
        - --repository-config=local/helm/repositories.yaml
    releases:
      - <<: *nats_release_base
        valuesFiles:
          - k8s/local-dev-values.yaml
          - k8s/cpc/values.yaml
          - k8s/cpc/cpc-2.yaml
